-- How Much Mate categories
-- 51 categories total: original 40 + 9 additions + 2 additions

INSERT INTO category (name, slug)
VALUES
    ('Plumbing', 'plumbing'),
    ('Electrical', 'electrical'),
    ('Roofing', 'roofing'),
    ('Carpentry', 'carpentry'),
    ('Painting', 'painting'),
    ('Tiling', 'tiling'),
    ('Flooring', 'flooring'),
    ('Concreting', 'concreting'),
    ('Bricklaying', 'bricklaying'),
    ('Waterproofing', 'waterproofing'),
    ('Fencing', 'fencing'),
    ('Decking', 'decking'),
    ('Car Care', 'car-care'),
    ('Home Maintenance', 'home-maintenance'),
    ('Landscaping & Gardening', 'landscaping-gardening'),
    ('Cleaning', 'cleaning'),
    ('Pest Control', 'pest-control'),
    ('Security & Automation', 'security-automation'),
    ('Appliance Services', 'appliance-services'),
    ('Health & Wellness', 'health-wellness'),
    ('Professional Services', 'professional-services'),
    ('Events & Lifestyle', 'events-lifestyle'),
    ('Pet Services', 'pet-services'),
    ('Trades & Construction', 'trades-construction'),
    ('Legal Services', 'legal-services'),
    ('Financial Services', 'financial-services'),
    ('IT & Tech Support', 'it-tech-support'),
    ('Marketing & Advertising', 'marketing-advertising'),
    ('Education & Tutoring', 'education-tutoring'),
    ('Travel & Tourism', 'travel-tourism'),
    ('Food & Catering', 'food-catering'),
    ('Retail & Shopping', 'retail-shopping'),
    ('Fitness & Sports', 'fitness-sports'),
    ('Arts & Entertainment', 'arts-entertainment'),
    ('Wellness & Spa', 'wellness-spa'),
    ('Photography & Videography', 'photography-videography'),
    ('Writing & Editing', 'writing-editing'),
    ('Translation Services', 'translation-services'),
    ('Consulting Services', 'consulting-services'),
    ('Real Estate Services', 'real-estate-services'),
    ('Moving & Removals', 'moving-removals'),
    ('Solar & Batteries', 'solar-batteries'),
    ('Heating & Air Conditioning', 'heating-air-conditioning'),
    ('Locksmiths', 'locksmiths'),
    ('Rubbish Removal', 'rubbish-removal'),
    ('Tree Services', 'tree-services'),
    ('Pools & Spas', 'pools-spas'),
    ('Windows & Glass', 'windows-glass'),
    ('Handyman', 'handyman'),
    ('Insulation', 'insulation'),
    ('Asbestos Removal', 'asbestos-removal');
