project_name    = "how-much-mate-dev"
organization_id = "cgdugjxdoazkaftxuluf"
region          = "ap-southeast-2"
auth_settings = {
  site_url                                   = "https://dev.howmuchmate.com.au"
  additional_redirect_urls                   = ["https://dev.howmuchmate.com.au/auth/callback", "https://dev.howmuchmate.com.au/auth/callback/password-recovery", "http://localhost:3000/auth/callback", "http://localhost:3000/auth/callback/password-recovery"]
  enable_refresh_token_rotation              = true
  enable_signup                              = true
  enable_anonymous_sign_ins                  = false
  minimum_password_length                    = 6
  mailer_otp_exp                             = 3600
  mailer_otp_length                          = 6
  smtp_admin_email                           = "hello@howmuchmate.com.au"
  smtp_sender_name                           = "Operations"
  smtp_host                                  = "sandbox.smtp.mailtrap.io"
  smtp_port                                  = "587"
  smtp_max_frequency                         = 10
  smtp_user                                  = "ee076af183dc09"
  security_captcha_enabled                   = true
  security_captcha_provider                  = "turnstile"
  external_google_client_id                  = "778035252919-s5c65jm6ksfbktq2uho6llghqn1pfidf.apps.googleusercontent.com"
  external_google_enabled                    = true
  mailer_templates_magic_link_content_path   = "../../../templates/magic-link.html"
  mailer_templates_confirmation_content_path = "../../../templates/confirmation.html"
  mailer_templates_recovery_content_path     = "../../../templates/recovery.html"
  hook_custom_access_token_enabled           = true
  hook_custom_access_token_uri               = "pg-functions://postgres/public/custom_access_token_hook"
}
