INSERT INTO category (name, slug)
VALUES 
('Plumbing', 'plumbing'),
('Electrical', 'electrical'),
('Roofing', 'roofing'),
('Carpentry', 'carpentry'),
('Painting', 'painting'),
('Tiling', 'tiling'),
('Flooring', 'flooring'),
('Concreting', 'concreting'),
('Bricklaying', 'bricklaying'),
('Waterproofing', 'waterproofing'),
('Fencing', 'fencing'),
('Decking', 'decking'),
('Car Care', 'car-care'),
('Home Maintenance', 'home-maintenance'),
('Landscaping & Gardening', 'landscaping-gardening'),
('Cleaning', 'cleaning'),
('Pest Control', 'pest-control'),
('Security & Automation', 'security-automation'),
('Appliance Services', 'appliance-services'),
('Health & Wellness', 'health-wellness'),
('Professional Services', 'professional-services'),
('Events & Lifestyle', 'events-lifestyle'),
('Pet Services', 'pet-services'),
('Trades & Construction', 'trades-construction'),
('Legal Services', 'legal-services'),
('Financial Services', 'financial-services'),
('IT & Tech Support', 'it-tech-support'),
('Marketing & Advertising', 'marketing-advertising'),
('Education & Tutoring', 'education-tutoring'),
('Travel & Tourism', 'travel-tourism'),
('Food & Catering', 'food-catering'),
('Retail & Shopping', 'retail-shopping'),
('Fitness & Sports', 'fitness-sports'),
('Arts & Entertainment', 'arts-entertainment'),
('Wellness & Spa', 'wellness-spa'),
('Photography & Videography', 'photography-videography'),
('Writing & Editing', 'writing-editing'),
('Translation Services', 'translation-services'),
('Consulting Services', 'consulting-services'),
('Real Estate Services', 'real-estate-services');