
  create table "public"."profile" (
    "profile_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text
      );


alter table "public"."profile" enable row level security;


  create table "public"."project" (
    "project_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "category" text,
    "profile_id" uuid not null
      );


alter table "public"."project" enable row level security;


  create table "public"."quote" (
    "quote_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "suburb_id" character varying,
    "profile_id" uuid,
    "project_id" uuid,
    "price" numeric,
    "business_name" text,
    "metadata" jsonb
      );


alter table "public"."quote" enable row level security;

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (profile_id);

CREATE UNIQUE INDEX project_pkey ON public.project USING btree (project_id);

CREATE UNIQUE INDEX quote_pkey ON public.quote USING btree (quote_id);

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."project" add constraint "project_pkey" PRIMARY KEY using index "project_pkey";

alter table "public"."quote" add constraint "quote_pkey" PRIMARY KEY using index "quote_pkey";

alter table "public"."profile" add constraint "profile_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_profile_id_fkey";

alter table "public"."project" add constraint "project_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profile(profile_id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."project" validate constraint "project_profile_id_fkey";

alter table "public"."quote" add constraint "quote_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profile(profile_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quote" validate constraint "quote_profile_id_fkey";

alter table "public"."quote" add constraint "quote_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.project(project_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."quote" validate constraint "quote_project_id_fkey";

grant delete on table "public"."profile" to "anon";

grant insert on table "public"."profile" to "anon";

grant references on table "public"."profile" to "anon";

grant select on table "public"."profile" to "anon";

grant trigger on table "public"."profile" to "anon";

grant truncate on table "public"."profile" to "anon";

grant update on table "public"."profile" to "anon";

grant delete on table "public"."profile" to "authenticated";

grant insert on table "public"."profile" to "authenticated";

grant references on table "public"."profile" to "authenticated";

grant select on table "public"."profile" to "authenticated";

grant trigger on table "public"."profile" to "authenticated";

grant truncate on table "public"."profile" to "authenticated";

grant update on table "public"."profile" to "authenticated";

grant delete on table "public"."profile" to "service_role";

grant insert on table "public"."profile" to "service_role";

grant references on table "public"."profile" to "service_role";

grant select on table "public"."profile" to "service_role";

grant trigger on table "public"."profile" to "service_role";

grant truncate on table "public"."profile" to "service_role";

grant update on table "public"."profile" to "service_role";

grant delete on table "public"."project" to "anon";

grant insert on table "public"."project" to "anon";

grant references on table "public"."project" to "anon";

grant select on table "public"."project" to "anon";

grant trigger on table "public"."project" to "anon";

grant truncate on table "public"."project" to "anon";

grant update on table "public"."project" to "anon";

grant delete on table "public"."project" to "authenticated";

grant insert on table "public"."project" to "authenticated";

grant references on table "public"."project" to "authenticated";

grant select on table "public"."project" to "authenticated";

grant trigger on table "public"."project" to "authenticated";

grant truncate on table "public"."project" to "authenticated";

grant update on table "public"."project" to "authenticated";

grant delete on table "public"."project" to "service_role";

grant insert on table "public"."project" to "service_role";

grant references on table "public"."project" to "service_role";

grant select on table "public"."project" to "service_role";

grant trigger on table "public"."project" to "service_role";

grant truncate on table "public"."project" to "service_role";

grant update on table "public"."project" to "service_role";

grant delete on table "public"."quote" to "anon";

grant insert on table "public"."quote" to "anon";

grant references on table "public"."quote" to "anon";

grant select on table "public"."quote" to "anon";

grant trigger on table "public"."quote" to "anon";

grant truncate on table "public"."quote" to "anon";

grant update on table "public"."quote" to "anon";

grant delete on table "public"."quote" to "authenticated";

grant insert on table "public"."quote" to "authenticated";

grant references on table "public"."quote" to "authenticated";

grant select on table "public"."quote" to "authenticated";

grant trigger on table "public"."quote" to "authenticated";

grant truncate on table "public"."quote" to "authenticated";

grant update on table "public"."quote" to "authenticated";

grant delete on table "public"."quote" to "service_role";

grant insert on table "public"."quote" to "service_role";

grant references on table "public"."quote" to "service_role";

grant select on table "public"."quote" to "service_role";

grant trigger on table "public"."quote" to "service_role";

grant truncate on table "public"."quote" to "service_role";

grant update on table "public"."quote" to "service_role";


