create type public.app_role as enum (
  'admin',
  'moderator'
);

create type public.app_permission as enum (
  'quotes.moderate',
  'quotes.delete_any',
  'categories.manage',
  'users.manage'
);

create table public.user_role (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  role public.app_role not null,
  unique (user_id, role)
);

comment on table public.user_role is
  'Application roles for each user.';

create table public.role_permission (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

comment on table public.role_permission is
  'Application permissions for each role.';

insert into public.role_permission (role, permission)
values
  ('moderator', 'quotes.moderate'),
  ('moderator', 'quotes.delete_any'),
  ('admin', 'quotes.moderate'),
  ('admin', 'quotes.delete_any'),
  ('admin', 'categories.manage'),
  ('admin', 'users.manage');
