create table
  "public"."category" (
    "category_id" bigint generated by default as identity not null,
    "created_at" timestamp
    with
      time zone not null default now (),
      "name" text not null,
      "slug" text not null
  );

alter table "public"."category" enable row level security;

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (category_id);

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

grant
select
  on table "public"."category" to "anon";

grant
select
  on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant
select
  on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant
update on table "public"."category" to "service_role";

create policy "Enable read access for all users" on "public"."category" as permissive for
select
  to public using (true);