create type public.app_role as enum (
  'admin',
  'moderator'
);

create type public.app_permission as enum (
  'quotes.moderate',
  'quotes.delete_any',
  'categories.manage',
  'users.manage'
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade not null,
  role public.app_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is
  'Application roles for each user.';

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

comment on table public.role_permissions is
  'Application permissions for each role.';
